name: Docker Image Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Docker Auth
        run: docker login docker.pkg.github.com -u ${GITHUB_ACTOR} -p ${{ secrets.GITHUB_TOKEN }}
      #      - name: Docker Build
      #        run: docker build -t docker.pkg.github.com/android-builder-action:latest $(pwd)
      - name: Docker Publish
        #if: startsWith(github.ref, 'refs/tags')
        run: |
          TAG=$(echo ${{ github.ref }} | sed 's/refs\/tags\/s*//')
          echo "TAG is ${TAG}"
#          docker push docker.pkg.github.com/android-builder-action:${TAG}