name: Docker Image Build

on: [push]

jobs:
  build:
    env:
      TAG_PREFIX: "docker.pkg.github.com/manimaul/android-builder-action/android-sdk"
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Docker Auth
        run: docker login docker.pkg.github.com -u ${GITHUB_ACTOR} -p ${{ secrets.GITHUB_TOKEN }}
      - name: Docker Build
        run: docker build -t android-sdk $(pwd)/android-sdk
      - name: Docker Publish Tag
        if: startsWith(github.ref, 'refs/tags')
        run: |
          TAG=$(echo ${{ github.ref }} | sed 's/refs\/tags\/s*//')
          echo "TAG is ${TAG}"
          docker tag android-sdk ${TAG_PREFIX}:${TAG}
          echo "pushing ${TAG_PREFIX}:${TAG}"
          docker push ${TAG_PREFIX}:${TAG}
      - name: Docker Publish Latest
        if: github.ref == 'refs/heads/master'
        run: |
          docker tag android-sdk ${TAG_PREFIX}:latest
          echo "pushing ${TAG_PREFIX}:latest"
          docker push ${TAG_PREFIX}:latest